// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"

// The following include is automatically generated by Unreal Header Tool (UHT).
// Ensure this file is processed by UHT and included in your build target's .Build.cs file.
// Do NOT manually create "SpellElement.generated.h".
#include "ESpellElement.generated.h"

/**
 * Element types for the refraction system
 */
UENUM(BlueprintType)
enum class ESpellElement : uint8
{
    Generic UMETA(DisplayName = "Generic"),
    Fire UMETA(DisplayName = "Fire"),
    Water UMETA(DisplayName = "Water"),
    Earth UMETA(DisplayName = "Earth"),
    Wind UMETA(DisplayName = "Wind"),
    Light UMETA(DisplayName = "Light"),
    Darkness UMETA(DisplayName = "Darkness"),
    Lightning UMETA(DisplayName = "Lightning"),
    Void UMETA(DisplayName = "Void"),
    Reality UMETA(DisplayName = "Reality"),
    // DEPRECATED as an innate-element data value — BD is now InnateElement=Darkness +
    // UCharacterData::bBrokenDarknessInnate. Kept (Hidden) until Phase 2 (asset re-save +
    // LoadoutComponent loop Max-sentinel). Still used as the DISPLAY identity by
    // GetDisplayElement() and as the LoadoutComponent loop upper bound — do NOT delete in Phase 1.
    BrokenDarkness UMETA(DisplayName = "Broken Darkness (Deprecated)", Hidden),
    // Dedicated non-elemental sentinel (value 11, appended after BrokenDarkness=10).
    // Takes over the "no element / default" job that Generic used to do — Generic is being
    // repurposed to "inherit the source element at cast time". Append-only: existing values
    // keep their numbers. Sits OUTSIDE the LoadoutComponent BD loop bound (<= BrokenDarkness),
    // so it is not iterated as an absorbable element.
    None UMETA(DisplayName = "None")
};