// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"

// The following include is automatically generated by Unreal Header Tool (UHT).
// Ensure this file is processed by UHT and included in your build target's .Build.cs file.
// Do NOT manually create "SpellElement.generated.h".
#include "ESpellElement.generated.h"

/**
 * Element types for the refraction system
 */
UENUM(BlueprintType)
enum class ESpellElement : uint8
{
    Generic UMETA(DisplayName = "Generic"),
    Fire UMETA(DisplayName = "Fire"),
    Water UMETA(DisplayName = "Water"),
    Earth UMETA(DisplayName = "Earth"),
    Wind UMETA(DisplayName = "Wind"),
    Light UMETA(DisplayName = "Light"),
    Darkness UMETA(DisplayName = "Darkness"),
    Lightning UMETA(DisplayName = "Lightning"),
    Void UMETA(DisplayName = "Void"),
    Reality UMETA(DisplayName = "Reality"),
    BrokenDarkness UMETA(DisplayName = "Broken Darkness")
};